// AUTO-GENERATED by scripts/build-types.ts — do not edit by hand.
// Run `npm run build:types` after changing src/lib/core/schema.ts.

/** Common fields PocketBase attaches to every record. */
export interface BaseRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: string;
}

export interface CategoriesRecord extends BaseRecord {
  name: string;
  icon?: string;
}

export interface PlayersRecord extends BaseRecord {
  email?: string;
  emailVisibility?: boolean;
  verified?: boolean;
  nickname: string;
  xp?: number;
  level: number;
  re_rolls?: number;
  favorite_categories?: string[];
}

export interface GamesRecord extends BaseRecord {
  name: string;
  min_players: number;
  max_players: number;
  categories?: string[];
  image?: string;
  description?: string;
  owned_by?: string[];
  created_by: string;
}

export interface AchievementsRecord extends BaseRecord {
  game: string;
  title: string;
  description: string;
  trigger_expr: string;
  rarity: "common" | "rare" | "epic" | "";
  icon?: string;
}

export interface SessionsRecord extends BaseRecord {
  host: string;
  co_host?: string;
  status: "created" | "active" | "ended" | "";
  started_at?: string;
  ended_at?: string;
  qr_token: string;
}

export interface SessionParticipantsRecord extends BaseRecord {
  session: string;
  player: string;
  status: "present" | "playing" | "spectator" | "kicked" | "left" | "";
  joined_at: string;
  left_at?: string;
}

export interface MatchesRecord extends BaseRecord {
  session: string;
  game?: string;
  status: "voting" | "playing" | "done" | "";
  started_at?: string;
  ended_at?: string;
  duration_seconds?: number;
  was_random?: boolean;
}

export interface MatchPlayersRecord extends BaseRecord {
  match: string;
  player: string;
  won?: boolean;
  rating?: "like" | "dislike" | "";
}

export interface VotesRecord extends BaseRecord {
  match: string;
  player: string;
  game?: string;
}

export interface PlayerAchievementsRecord extends BaseRecord {
  player: string;
  achievement: string;
  unlocked_at: string;
}

export interface AvailabilitiesRecord extends BaseRecord {
  player: string;
  role: "host" | "player" | "";
  weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun" | "";
  start_hour: number;
  end_hour: number;
  capacity?: number;
  max_group_size?: number;
}

export interface MatchProposalsRecord extends BaseRecord {
  weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun" | "";
  start_hour: number;
  end_hour: number;
  proposed_date: string;
  host: string;
  status: "proposed" | "confirmed" | "cancelled" | "expired" | "";
  session?: string;
}

export interface InvitesRecord extends BaseRecord {
  proposal: string;
  player: string;
  response: "pending" | "accepted" | "declined" | "";
  invite_token: string;
  responded_at?: string;
}

export interface PushSubscriptionsRecord extends BaseRecord {
  player: string;
  endpoint: string;
  p256dh: string;
  auth: string;
}

/** Maps a collection name to its strongly-typed record. */
export interface CollectionRecordMap {
  categories: CategoriesRecord;
  players: PlayersRecord;
  games: GamesRecord;
  achievements: AchievementsRecord;
  sessions: SessionsRecord;
  session_participants: SessionParticipantsRecord;
  matches: MatchesRecord;
  match_players: MatchPlayersRecord;
  votes: VotesRecord;
  player_achievements: PlayerAchievementsRecord;
  availabilities: AvailabilitiesRecord;
  match_proposals: MatchProposalsRecord;
  invites: InvitesRecord;
  push_subscriptions: PushSubscriptionsRecord;
}

export type CollectionName = keyof CollectionRecordMap;
