// AUTO-GENERATED by scripts/build-migrations.ts — do not edit by hand.
/// <reference path="../pb_data/types.d.ts" />

migrate(
  (app) => {
    const collections = [
      {
        "name": "categories",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "name",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 2,
            "max": 30,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "icon",
            "type": "text",
            "required": false,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 20,
            "pattern": "",
            "primaryKey": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "name": "users",
        "type": "auth",
        "system": false,
        "fields": [
          {
            "name": "nickname",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 2,
            "max": 24,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "xp",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 0,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "level",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "re_rolls",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 0,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "favorite_categories",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "categories",
            "maxSelect": null,
            "minSelect": null,
            "cascadeDelete": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": "id = @request.auth.id",
        "deleteRule": null,
        "passwordAuth": {
          "enabled": true,
          "identityFields": [
            "username"
          ]
        },
        "oauth2": {
          "enabled": false,
          "providers": []
        },
        "manageRule": null,
        "authRule": ""
      },
      {
        "name": "games",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "name",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 80,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "min_players",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "max_players",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "categories",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "categories",
            "maxSelect": null,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "image",
            "type": "file",
            "required": false,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "maxSize": 2097152,
            "mimeTypes": [],
            "thumbs": [],
            "protected": false
          },
          {
            "name": "description",
            "type": "text",
            "required": false,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 500,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "owned_by",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": null,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "created_by",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": "@request.auth.id != \"\"",
        "updateRule": "created_by = @request.auth.id",
        "deleteRule": "created_by = @request.auth.id"
      },
      {
        "name": "achievements",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "game",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "games",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": true
          },
          {
            "name": "title",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 80,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "description",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 300,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "trigger_expr",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 500,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "rarity",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "common",
              "rare",
              "epic"
            ]
          },
          {
            "name": "icon",
            "type": "text",
            "required": false,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 20,
            "pattern": "",
            "primaryKey": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "name": "sessions",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "host",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "co_host",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "status",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "created",
              "active",
              "ended"
            ]
          },
          {
            "name": "started_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "ended_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "qr_token",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 8,
            "max": 64,
            "pattern": "",
            "primaryKey": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": "@request.auth.id != \"\"",
        "updateRule": "host = @request.auth.id",
        "deleteRule": "host = @request.auth.id"
      },
      {
        "name": "session_participants",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "session",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "sessions",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": true
          },
          {
            "name": "user",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "status",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "present",
              "playing",
              "spectator",
              "kicked",
              "left"
            ]
          },
          {
            "name": "joined_at",
            "type": "date",
            "required": true,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "left_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_sp_session_user ON session_participants (session, user)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "name": "matches",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "session",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "sessions",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": true
          },
          {
            "name": "game",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "games",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "status",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "voting",
              "playing",
              "done"
            ]
          },
          {
            "name": "started_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "ended_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "duration_seconds",
            "type": "number",
            "required": false,
            "presentable": false,
            "system": false,
            "min": 0,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "was_random",
            "type": "bool",
            "required": false,
            "presentable": false,
            "system": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "name": "match_players",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "match",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "matches",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": true
          },
          {
            "name": "user",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "won",
            "type": "bool",
            "required": false,
            "presentable": false,
            "system": false
          },
          {
            "name": "liked",
            "type": "bool",
            "required": false,
            "presentable": false,
            "system": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_mp_match_user ON match_players (match, user)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "name": "votes",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "match",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "matches",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": true
          },
          {
            "name": "user",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          },
          {
            "name": "game",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "games",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_votes_match_user ON votes (match, user)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "name": "user_achievements",
        "type": "base",
        "system": false,
        "fields": [
          {
            "name": "user",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "users",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": true
          },
          {
            "name": "achievement",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "achievements",
            "maxSelect": 1,
            "minSelect": null,
            "cascadeDelete": true
          },
          {
            "name": "unlocked_at",
            "type": "date",
            "required": true,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_ua_user_achievement ON user_achievements (user, achievement)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      }
    ];
    for (const data of collections) {
      const collection = new Collection(data);
      app.save(collection);
    }
  },
  (app) => {
    const names = ["user_achievements","votes","match_players","matches","session_participants","sessions","achievements","games","users","categories"];
    for (const name of names) {
      try {
        const collection = app.findCollectionByNameOrId(name);
        app.delete(collection);
      } catch (_) { /* already gone */ }
    }
  },
);
