// AUTO-GENERATED by scripts/build-migrations.ts — do not edit by hand.
/// <reference path="../pb_data/types.d.ts" />

migrate(
  (app) => {
    const collections = [
      {
        "id": "pbc_categories0",
        "name": "categories",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "name",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 2,
            "max": 30,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "icon",
            "type": "text",
            "required": false,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 20,
            "pattern": "",
            "primaryKey": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_categories_name ON categories (name)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "id": "pbc_players0000",
        "name": "players",
        "type": "auth",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "password901924565",
            "name": "password",
            "type": "password",
            "system": true,
            "hidden": true,
            "required": true,
            "presentable": false,
            "min": 4,
            "max": 71,
            "pattern": "",
            "cost": 0
          },
          {
            "id": "text2504183744",
            "name": "tokenKey",
            "type": "text",
            "system": true,
            "hidden": true,
            "required": true,
            "presentable": false,
            "min": 30,
            "max": 60,
            "pattern": "",
            "autogeneratePattern": "[a-zA-Z0-9_]{50}"
          },
          {
            "id": "email3885137012",
            "name": "email",
            "type": "email",
            "system": true,
            "hidden": false,
            "required": false,
            "presentable": false,
            "onlyDomains": null,
            "exceptDomains": null
          },
          {
            "id": "bool1547992806",
            "name": "emailVisibility",
            "type": "bool",
            "system": true,
            "hidden": false,
            "required": false,
            "presentable": false
          },
          {
            "id": "bool256245529",
            "name": "verified",
            "type": "bool",
            "system": true,
            "hidden": false,
            "required": false,
            "presentable": false
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "nickname",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 2,
            "max": 24,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "xp",
            "type": "number",
            "required": false,
            "presentable": false,
            "system": false,
            "min": 0,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "level",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "re_rolls",
            "type": "number",
            "required": false,
            "presentable": false,
            "system": false,
            "min": 0,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "favorite_categories",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_categories0",
            "maxSelect": 0,
            "minSelect": 0,
            "cascadeDelete": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_players_nickname ON players (nickname)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": "",
        "updateRule": "id = @request.auth.id",
        "deleteRule": null,
        "passwordAuth": {
          "enabled": true,
          "identityFields": [
            "nickname"
          ]
        },
        "oauth2": {
          "enabled": false,
          "providers": []
        },
        "mfa": {
          "enabled": false,
          "duration": 0,
          "rule": ""
        },
        "otp": {
          "enabled": false
        },
        "manageRule": null,
        "authRule": "",
        "authToken": {
          "duration": 1209600
        },
        "passwordResetToken": {
          "duration": 1800
        },
        "emailChangeToken": {
          "duration": 1800
        },
        "verificationToken": {
          "duration": 259200
        },
        "fileToken": {
          "duration": 180
        }
      },
      {
        "id": "pbc_games000000",
        "name": "games",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "name",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 80,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "min_players",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "max_players",
            "type": "number",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "categories",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_categories0",
            "maxSelect": 0,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "image",
            "type": "file",
            "required": false,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "maxSize": 2097152,
            "mimeTypes": [],
            "thumbs": [],
            "protected": false
          },
          {
            "name": "description",
            "type": "text",
            "required": false,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 500,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "owned_by",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 0,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "created_by",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_games_name ON games (name)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": "@request.auth.id != \"\"",
        "updateRule": "created_by = @request.auth.id",
        "deleteRule": "created_by = @request.auth.id"
      },
      {
        "id": "pbc_achievement",
        "name": "achievements",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "game",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_games000000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "title",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 80,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "description",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 300,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "trigger_expr",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": 500,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "rarity",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "common",
              "rare",
              "epic"
            ]
          },
          {
            "name": "icon",
            "type": "text",
            "required": false,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 20,
            "pattern": "",
            "primaryKey": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "id": "pbc_sessions000",
        "name": "sessions",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "host",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "co_host",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "status",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "created",
              "active",
              "ended"
            ]
          },
          {
            "name": "started_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "ended_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "qr_token",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 8,
            "max": 64,
            "pattern": "",
            "primaryKey": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_sessions_qr_token ON sessions (qr_token)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": "@request.auth.id != \"\"",
        "updateRule": "host = @request.auth.id",
        "deleteRule": "host = @request.auth.id"
      },
      {
        "id": "pbc_session_par",
        "name": "session_participants",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "session",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_sessions000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "status",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "present",
              "playing",
              "spectator",
              "kicked",
              "left"
            ]
          },
          {
            "name": "joined_at",
            "type": "date",
            "required": true,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "left_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_sp_session_player ON session_participants (session, player)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "id": "pbc_matches0000",
        "name": "matches",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "session",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_sessions000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "game",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_games000000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "status",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "voting",
              "playing",
              "done"
            ]
          },
          {
            "name": "started_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "ended_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "duration_seconds",
            "type": "number",
            "required": false,
            "presentable": false,
            "system": false,
            "min": 0,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "was_random",
            "type": "bool",
            "required": false,
            "presentable": false,
            "system": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "id": "pbc_match_playe",
        "name": "match_players",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "match",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_matches0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "won",
            "type": "bool",
            "required": false,
            "presentable": false,
            "system": false
          },
          {
            "name": "rating",
            "type": "select",
            "required": false,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "like",
              "dislike"
            ]
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_mp_match_player ON match_players (match, player)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "id": "pbc_votes000000",
        "name": "votes",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "match",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_matches0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "game",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_games000000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_votes_match_player ON votes (match, player)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      },
      {
        "id": "pbc_player_achi",
        "name": "player_achievements",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "achievement",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_achievement",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "unlocked_at",
            "type": "date",
            "required": true,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_pa_player_achievement ON player_achievements (player, achievement)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null
      }
    ];
    for (const data of collections) {
      const collection = new Collection(data);
      app.save(collection);
    }
  },
  (app) => {
    const names = ["player_achievements","votes","match_players","matches","session_participants","sessions","achievements","games","players","categories"];
    for (const name of names) {
      try {
        const collection = app.findCollectionByNameOrId(name);
        app.delete(collection);
      } catch (_) { /* already gone */ }
    }
  },
);
