// AUTO-GENERATED by scripts/build-migrations.ts — do not edit by hand.
/// <reference path="../pb_data/types.d.ts" />

migrate(
  (app) => {
    const collections = [
      {
        "id": "pbc_availabilit",
        "name": "availabilities",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "role",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "host",
              "player"
            ]
          },
          {
            "name": "weekday",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "mon",
              "tue",
              "wed",
              "thu",
              "fri",
              "sat",
              "sun"
            ]
          },
          {
            "name": "time_slot",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "morning",
              "afternoon",
              "evening",
              "night"
            ]
          },
          {
            "name": "capacity",
            "type": "number",
            "required": false,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          },
          {
            "name": "max_group_size",
            "type": "number",
            "required": false,
            "presentable": false,
            "system": false,
            "min": 1,
            "max": null,
            "onlyInt": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_avail_player_role_slot ON availabilities (player, role, weekday, time_slot)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": "player = @request.auth.id",
        "updateRule": "player = @request.auth.id",
        "deleteRule": "player = @request.auth.id"
      },
      {
        "id": "pbc_match_propo",
        "name": "match_proposals",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "weekday",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "mon",
              "tue",
              "wed",
              "thu",
              "fri",
              "sat",
              "sun"
            ]
          },
          {
            "name": "time_slot",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "morning",
              "afternoon",
              "evening",
              "night"
            ]
          },
          {
            "name": "proposed_date",
            "type": "date",
            "required": true,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          },
          {
            "name": "host",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "status",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "proposed",
              "confirmed",
              "cancelled",
              "expired"
            ]
          },
          {
            "name": "session",
            "type": "relation",
            "required": false,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_sessions000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": "host = @request.auth.id",
        "deleteRule": null
      },
      {
        "id": "pbc_invites0000",
        "name": "invites",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "proposal",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_match_propo",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": false
          },
          {
            "name": "response",
            "type": "select",
            "required": true,
            "presentable": false,
            "system": false,
            "maxSelect": 1,
            "values": [
              "pending",
              "accepted",
              "declined"
            ]
          },
          {
            "name": "invite_token",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 8,
            "max": 64,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "responded_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_invites_invite_token ON invites (invite_token)",
          "CREATE UNIQUE INDEX idx_invites_proposal_player ON invites (proposal, player)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": "invite_token = @request.query.token && response = \"pending\"",
        "deleteRule": null
      },
      {
        "id": "pbc_push_subscr",
        "name": "push_subscriptions",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "endpoint",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 500,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "p256dh",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 300,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "auth",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": null,
            "max": 100,
            "pattern": "",
            "primaryKey": false
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_push_player_endpoint ON push_subscriptions (player, endpoint)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": "player = @request.auth.id",
        "updateRule": "player = @request.auth.id",
        "deleteRule": "player = @request.auth.id"
      }
    ];
    for (const data of collections) {
      const collection = new Collection(data);
      app.save(collection);
    }
  },
  (app) => {
    const names = ["push_subscriptions","invites","match_proposals","availabilities"];
    for (const name of names) {
      try {
        const collection = app.findCollectionByNameOrId(name);
        app.delete(collection);
      } catch (_) { /* already gone */ }
    }
  },
);
