// AUTO-GENERATED by scripts/build-migrations.ts — do not edit by hand.
/// <reference path="../pb_data/types.d.ts" />

migrate(
  (app) => {
    const collections = [
      {
        "id": "pbc_piles_claim",
        "name": "piles_claims",
        "type": "base",
        "system": false,
        "fields": [
          {
            "id": "text3208210256",
            "name": "id",
            "type": "text",
            "system": true,
            "required": true,
            "presentable": false,
            "primaryKey": true,
            "hidden": false,
            "min": 15,
            "max": 15,
            "pattern": "^[a-z0-9]+$",
            "autogeneratePattern": "[a-z0-9]{15}"
          },
          {
            "id": "autodate2990389176",
            "name": "created",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": false
          },
          {
            "id": "autodate3332085495",
            "name": "updated",
            "type": "autodate",
            "system": true,
            "hidden": false,
            "presentable": false,
            "onCreate": true,
            "onUpdate": true
          },
          {
            "name": "player",
            "type": "relation",
            "required": true,
            "presentable": false,
            "system": false,
            "collectionId": "pbc_players0000",
            "maxSelect": 1,
            "minSelect": 0,
            "cascadeDelete": true
          },
          {
            "name": "code",
            "type": "text",
            "required": true,
            "presentable": false,
            "system": false,
            "min": 6,
            "max": 12,
            "pattern": "",
            "primaryKey": false
          },
          {
            "name": "consumed_at",
            "type": "date",
            "required": false,
            "presentable": false,
            "system": false,
            "min": "",
            "max": ""
          }
        ],
        "indexes": [
          "CREATE UNIQUE INDEX idx_piles_claims_code ON piles_claims (code)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": "player = @request.auth.id",
        "updateRule": null,
        "deleteRule": "player = @request.auth.id"
      }
    ];
    for (const data of collections) {
      const collection = new Collection(data);
      app.save(collection);
    }
  },
  (app) => {
    const names = ["piles_claims"];
    for (const name of names) {
      try {
        const collection = app.findCollectionByNameOrId(name);
        app.delete(collection);
      } catch (_) { /* already gone */ }
    }
  },
);
