/**
 * Bundle the shared core library into a CommonJS file that PocketBase's
 * embedded Goja runtime can `require()` from hook files.
 *
 * Output: pb_hooks/_core.js
 *
 * Target es2020 because Goja (as of PocketBase 0.22+) implements most of
 * ES2020. Keep format=cjs because PocketBase hooks use `require()`.
 */

import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const ENTRY = join(ROOT, "src", "lib", "core", "hooks-entry.ts");
const OUT_DIR = join(ROOT, "pb_hooks");
const OUT_FILE = join(OUT_DIR, "_core.js");

export const BUILD_OPTIONS: esbuild.BuildOptions = {
  entryPoints: [ENTRY],
  outfile: OUT_FILE,
  bundle: true,
  format: "cjs",
  platform: "neutral",
  target: "es2020",
  minify: false,
  sourcemap: false,
  legalComments: "none",
  logLevel: "silent",
  banner: {
    js: "// AUTO-GENERATED by scripts/build-hooks.ts — do not edit by hand.\n",
  },
};

export async function buildHooks(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });
  await esbuild.build(BUILD_OPTIONS);
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  buildHooks()
    .then(() => console.log(`[build-hooks] wrote ${OUT_FILE.replace(ROOT, ".")}`))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
