/**
 * Generate the PocketBase JS migration(s) from src/lib/core/schema.ts.
 *
 * Run via `npm run build:migrations`. The output is deterministic so CI can
 * run the generator and assert `git diff --exit-code pb_migrations/`.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  AUTH_OPTIONS,
  COLLECTIONS,
  type CollectionDef,
  type FieldDef,
  validateSchema,
} from "../src/lib/core/schema.js";

export interface MigrationOptions {
  /** Stable timestamp prefix for the init migration filename. */
  timestamp: number;
  /** Name component of the filename, e.g. "init". */
  name: string;
}

const INIT_OPTIONS: MigrationOptions = {
  timestamp: 1700000000,
  name: "init",
};

export function buildInitMigration(
  collections: readonly CollectionDef[] = COLLECTIONS,
): string {
  const errors = validateSchema(collections);
  if (errors.length > 0) {
    throw new Error(
      "Schema validation failed:\n" +
        errors.map((e) => `  - ${e.path}: ${e.message}`).join("\n"),
    );
  }

  const payload = collections.map((c) => collectionToJson(c));
  const json = JSON.stringify(payload, null, 2);

  return [
    "// AUTO-GENERATED by scripts/build-migrations.ts — do not edit by hand.",
    '/// <reference path="../pb_data/types.d.ts" />',
    "",
    "migrate(",
    "  (app) => {",
    `    const collections = ${indent(json, 4).trimStart()};`,
    "    for (const data of collections) {",
    "      const collection = new Collection(data);",
    "      app.save(collection);",
    "    }",
    "  },",
    "  (app) => {",
    `    const names = ${JSON.stringify(
      [...collections].map((c) => c.name).reverse(),
    )};`,
    "    for (const name of names) {",
    "      try {",
    "        const collection = app.findCollectionByNameOrId(name);",
    "        app.delete(collection);",
    "      } catch (_) { /* already gone */ }",
    "    }",
    "  },",
    ");",
    "",
  ].join("\n");
}

function collectionToJson(c: CollectionDef): Record<string, unknown> {
  const base: Record<string, unknown> = {
    name: c.name,
    type: c.type ?? "base",
    system: false,
    fields: c.fields.map(fieldToJson),
    indexes: [...(c.indexes ?? [])],
    listRule: c.listRule ?? null,
    viewRule: c.viewRule ?? null,
    createRule: c.createRule ?? null,
    updateRule: c.updateRule ?? null,
    deleteRule: c.deleteRule ?? null,
  };
  if (c.type === "auth") {
    base.passwordAuth = {
      enabled: AUTH_OPTIONS.allowUsernameAuth || AUTH_OPTIONS.allowEmailAuth,
      identityFields: AUTH_OPTIONS.allowUsernameAuth
        ? ["username"]
        : ["email"],
    };
    base.oauth2 = { enabled: false, providers: [] };
    base.manageRule = null;
    base.authRule = "";
  }
  return base;
}

function fieldToJson(f: FieldDef): Record<string, unknown> {
  const common: Record<string, unknown> = {
    name: f.name,
    type: f.type,
    required: f.required ?? false,
    presentable: false,
    system: false,
  };

  switch (f.type) {
    case "text":
      return {
        ...common,
        min: f.min ?? null,
        max: f.max ?? null,
        pattern: "",
        primaryKey: false,
      };
    case "number":
      return {
        ...common,
        min: f.min ?? null,
        max: f.max ?? null,
        onlyInt: false,
      };
    case "bool":
      return common;
    case "date":
      return { ...common, min: "", max: "" };
    case "json":
      return { ...common, maxSize: f.maxSize ?? 2_000_000 };
    case "select":
      return {
        ...common,
        maxSelect: f.maxSelect ?? 1,
        values: [...(f.options ?? [])],
      };
    case "relation":
      return {
        ...common,
        collectionId: f.relationTo!,
        maxSelect: f.maxSelect ?? null,
        minSelect: null,
        cascadeDelete: f.cascadeDelete ?? false,
      };
    case "file":
      return {
        ...common,
        maxSelect: f.maxSelect ?? 1,
        maxSize: f.maxSize ?? 5_242_880,
        mimeTypes: [],
        thumbs: [],
        protected: false,
      };
  }
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length === 0 ? line : pad + line))
    .join("\n");
}

function migrationFilename(opts: MigrationOptions): string {
  return `${opts.timestamp}_${opts.name}.js`;
}

function repoRoot(): string {
  return dirname(dirname(fileURLToPath(import.meta.url)));
}

export function writeInitMigration(
  opts: MigrationOptions = INIT_OPTIONS,
  collections: readonly CollectionDef[] = COLLECTIONS,
): { path: string; contents: string; changed: boolean } {
  const root = repoRoot();
  const dir = join(root, "pb_migrations");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, migrationFilename(opts));
  const contents = buildInitMigration(collections);
  let previous = "";
  try {
    previous = readFileSync(path, "utf8");
  } catch {
    // first run
  }
  if (previous === contents) {
    return { path, contents, changed: false };
  }
  writeFileSync(path, contents, "utf8");
  return { path, contents, changed: true };
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const result = writeInitMigration();
  const rel = result.path.replace(repoRoot() + "\\", "").replace(repoRoot() + "/", "");
  if (result.changed) {
    console.log(`[build-migrations] wrote ${rel}`);
  } else {
    console.log(`[build-migrations] no changes: ${rel}`);
  }
}
