/**
 * Generate src/lib/core/records.ts from the schema manifest.
 *
 * Each collection becomes a TypeScript interface that mirrors the
 * record shape returned by the PocketBase REST/SDK (snake_case fields
 * + `id`, `created`, `updated`, `collectionId`, `collectionName`).
 *
 * The output is committed and CI re-runs `build:types` to assert no
 * drift, mirroring how we treat the migration and hook bundles.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  COLLECTIONS,
  type CollectionDef,
  type FieldDef,
} from "../src/lib/core/schema.js";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_FILE = join(ROOT, "src", "lib", "core", "records.ts");

function pascal(snake: string): string {
  return snake
    .split("_")
    .map((p) => (p.length ? p[0]!.toUpperCase() + p.slice(1) : ""))
    .join("");
}

function recordTypeName(collectionName: string): string {
  return `${pascal(collectionName)}Record`;
}

function tsType(field: FieldDef): string {
  switch (field.type) {
    case "text":
      return "string";
    case "number":
      return "number";
    case "bool":
      return "boolean";
    case "date":
      return "string";
    case "json":
      return "unknown";
    case "file":
      return field.maxSelect === 1 ? "string" : "string[]";
    case "select": {
      const opts = (field.options ?? []).map((o) => `"${o}"`).join(" | ") || "string";
      return field.maxSelect === 1 ? `${opts} | ""` : `Array<${opts}>`;
    }
    case "relation":
      return field.maxSelect === 1 ? "string" : "string[]";
  }
}

function fieldLine(field: FieldDef): string {
  const type = tsType(field);
  // Required + non-zero-friendly fields are always present; everything
  // else (rating, optional file, optional relation) is `?`.
  const optional = !field.required;
  return `  ${field.name}${optional ? "?" : ""}: ${type};`;
}

function collectionInterface(c: CollectionDef): string {
  const lines = [`export interface ${recordTypeName(c.name)} extends BaseRecord {`];
  if (c.type === "auth") {
    lines.push("  email?: string;");
    lines.push("  emailVisibility?: boolean;");
    lines.push("  verified?: boolean;");
  }
  for (const f of c.fields) {
    lines.push(fieldLine(f));
  }
  lines.push("}");
  return lines.join("\n");
}

export function buildRecordsModule(
  collections: readonly CollectionDef[] = COLLECTIONS,
): string {
  const interfaces = collections.map(collectionInterface).join("\n\n");
  const mapEntries = collections
    .map((c) => `  ${c.name}: ${recordTypeName(c.name)};`)
    .join("\n");

  return [
    "// AUTO-GENERATED by scripts/build-types.ts — do not edit by hand.",
    "// Run `npm run build:types` after changing src/lib/core/schema.ts.",
    "",
    "/** Common fields PocketBase attaches to every record. */",
    "export interface BaseRecord {",
    "  id: string;",
    "  created: string;",
    "  updated: string;",
    "  collectionId: string;",
    "  collectionName: string;",
    "}",
    "",
    interfaces,
    "",
    "/** Maps a collection name to its strongly-typed record. */",
    "export interface CollectionRecordMap {",
    mapEntries,
    "}",
    "",
    "export type CollectionName = keyof CollectionRecordMap;",
    "",
  ].join("\n");
}

export function writeRecordsModule(
  collections: readonly CollectionDef[] = COLLECTIONS,
): { path: string; changed: boolean } {
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  const contents = buildRecordsModule(collections);
  let previous = "";
  try {
    previous = readFileSync(OUT_FILE, "utf8");
  } catch {
    // first run
  }
  if (previous === contents) return { path: OUT_FILE, changed: false };
  writeFileSync(OUT_FILE, contents, "utf8");
  return { path: OUT_FILE, changed: true };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const r = writeRecordsModule();
  const rel = r.path.replace(ROOT, ".");
  console.log(`[build-types] ${r.changed ? "wrote" : "no changes:"} ${rel}`);
}
