// AUTO-GENERATED by scripts/build-hooks.ts — do not edit by hand.

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/lib/core/hooks-entry.ts
var hooks_entry_exports = {};
__export(hooks_entry_exports, {
  RANDOM_VOTE: () => RANDOM_VOTE,
  computeMatchAwards: () => computeMatchAwards,
  emptyStats: () => emptyStats,
  evaluateTrigger: () => evaluateTrigger,
  levelFromXp: () => levelFromXp,
  progressToNextLevel: () => progressToNextLevel,
  resolveVotes: () => resolveVotes,
  xpForAction: () => xpForAction
});
module.exports = __toCommonJS(hooks_entry_exports);

// src/lib/core/achievements.ts
var TWO_CHAR_OPS = /* @__PURE__ */ new Set(["&&", "||", ">=", "<=", "==", "!="]);
var ONE_CHAR_OPS = /* @__PURE__ */ new Set(["(", ")", ">", "<"]);
function tokenize(input) {
  const tokens = [];
  let i = 0;
  while (i < input.length) {
    const c = input[i];
    if (c === " " || c === "	" || c === "\n" || c === "\r") {
      i++;
      continue;
    }
    if (/\d/.test(c)) {
      let j = i;
      let sawDot = false;
      while (j < input.length) {
        const cj = input[j];
        if (cj === ".") {
          if (sawDot) throw new Error("multiple dots in number");
          sawDot = true;
          j++;
        } else if (/\d/.test(cj)) {
          j++;
        } else {
          break;
        }
      }
      tokens.push({ type: "NUM", value: input.slice(i, j) });
      i = j;
      continue;
    }
    if (/[a-zA-Z_]/.test(c)) {
      let j = i;
      while (j < input.length && /\w/.test(input[j])) j++;
      tokens.push({ type: "IDENT", value: input.slice(i, j) });
      i = j;
      continue;
    }
    const two = input.slice(i, i + 2);
    if (TWO_CHAR_OPS.has(two)) {
      tokens.push({ type: two, value: two });
      i += 2;
      continue;
    }
    if (ONE_CHAR_OPS.has(c)) {
      tokens.push({ type: c, value: c });
      i++;
      continue;
    }
    throw new Error(`unexpected character: ${c}`);
  }
  return tokens;
}
var Parser = class {
  constructor(tokens, stats) {
    this.tokens = tokens;
    this.stats = stats;
    __publicField(this, "pos", 0);
  }
  peek() {
    return this.tokens[this.pos];
  }
  consume() {
    const t = this.tokens[this.pos++];
    if (!t) throw new Error("unexpected end of expression");
    return t;
  }
  parseExpr() {
    return this.parseOr();
  }
  parseOr() {
    let left = this.parseAnd();
    while (this.peek()?.type === "||") {
      this.consume();
      const right = this.parseAnd();
      left = left || right;
    }
    return left;
  }
  parseAnd() {
    let left = this.parseCmp();
    while (this.peek()?.type === "&&") {
      this.consume();
      const right = this.parseCmp();
      left = left && right;
    }
    return left;
  }
  parseCmp() {
    const left = this.parsePrimary();
    const op = this.peek();
    if (op && [">=", "<=", ">", "<", "==", "!="].includes(op.type)) {
      this.consume();
      const right = this.parsePrimary();
      switch (op.type) {
        case ">=":
          return left >= right;
        case "<=":
          return left <= right;
        case ">":
          return left > right;
        case "<":
          return left < right;
        case "==":
          return left === right;
        case "!=":
          return left !== right;
      }
    }
    return left !== 0;
  }
  parsePrimary() {
    const t = this.consume();
    if (t.type === "NUM") return parseFloat(t.value);
    if (t.type === "IDENT") return this.stats[t.value] ?? 0;
    if (t.type === "(") {
      const val = this.parseExpr();
      const close = this.consume();
      if (close.type !== ")") throw new Error("expected )");
      return val ? 1 : 0;
    }
    throw new Error(`unexpected token: ${t.type}`);
  }
  atEnd() {
    return this.pos >= this.tokens.length;
  }
};
function evaluateTrigger(expr, stats) {
  try {
    const tokens = tokenize(expr);
    if (tokens.length === 0) return false;
    const parser = new Parser(tokens, stats);
    const result = parser.parseExpr();
    if (!parser.atEnd()) return false;
    return result;
  } catch {
    return false;
  }
}

// src/lib/core/xp.ts
var XP_PER_ACTION = {
  participate_match: 10,
  win_match: 15,
  rate_game: 2,
  host_session: 50,
  co_host_session: 30,
  add_game: 25,
  achievement_common: 10,
  achievement_rare: 25,
  achievement_epic: 50
};
function xpForAction(action) {
  return XP_PER_ACTION[action];
}
function xpForLevel(level) {
  if (!Number.isInteger(level) || level < 1) {
    throw new Error(`level must be an integer >= 1, got ${level}`);
  }
  let total = 0;
  for (let k = 1; k < level; k++) {
    total += Math.floor(100 * Math.pow(k, 1.5));
  }
  return total;
}
function levelFromXp(xp) {
  if (xp <= 0) return 1;
  let lvl = 1;
  while (xpForLevel(lvl + 1) <= xp) {
    lvl++;
  }
  return lvl;
}
function progressToNextLevel(xp) {
  const level = levelFromXp(xp);
  const base = xpForLevel(level);
  const next = xpForLevel(level + 1);
  const into = xp - base;
  const needed = next - base;
  return { level, into, needed, ratio: into / needed };
}

// src/lib/core/awards.ts
function emptyStats(userId) {
  return {
    userId,
    totalWins: 0,
    winsOnGame: 0,
    lossesOnGame: 0,
    currentStreakWins: 0,
    currentStreakLosses: 0
  };
}
var RARITY_TO_ACTION = {
  common: "achievement_common",
  rare: "achievement_rare",
  epic: "achievement_epic"
};
function computeMatchAwards(outcome, statsByUser, achievementsForGame, alreadyUnlocked) {
  const results = [];
  for (const player of outcome.players) {
    const lines = [];
    lines.push({
      action: "participate_match",
      xp: xpForAction("participate_match")
    });
    if (player.won) {
      lines.push({ action: "win_match", xp: xpForAction("win_match") });
    }
    if (player.liked === true || player.liked === false) {
      lines.push({ action: "rate_game", xp: xpForAction("rate_game") });
    }
    const prev = statsByUser[player.userId] ?? emptyStats(player.userId);
    const postStats = advanceStats(prev, player.won, outcome.durationSeconds);
    const existing = alreadyUnlocked[player.userId] ?? /* @__PURE__ */ new Set();
    const unlocked = [];
    for (const ach of achievementsForGame) {
      if (existing.has(ach.id)) continue;
      if (evaluateTrigger(ach.triggerExpr, postStats)) {
        unlocked.push(ach.id);
        const action = RARITY_TO_ACTION[ach.rarity];
        lines.push({ action, xp: xpForAction(action) });
      }
    }
    const xpDelta = lines.reduce((sum, line) => sum + line.xp, 0);
    results.push({
      userId: player.userId,
      xpDelta,
      xpBreakdown: lines,
      unlockedAchievementIds: unlocked
    });
  }
  return results;
}
function advanceStats(prev, won, durationSeconds) {
  return {
    total_wins: prev.totalWins + (won ? 1 : 0),
    wins_on_game: prev.winsOnGame + (won ? 1 : 0),
    losses_on_game: prev.lossesOnGame + (won ? 0 : 1),
    current_streak_wins: won ? prev.currentStreakWins + 1 : 0,
    current_streak_losses: won ? 0 : prev.currentStreakLosses + 1,
    match_duration_seconds: durationSeconds,
    match_duration_minutes: durationSeconds / 60
  };
}

// src/lib/core/voting.ts
var RANDOM_VOTE = "__random__";
function resolveVotes(votes, eligibleGameIds, rand = Math.random) {
  if (votes.length === 0) return { kind: "no_votes" };
  const counts = /* @__PURE__ */ new Map();
  for (const v of votes) {
    counts.set(v.gameId, (counts.get(v.gameId) ?? 0) + 1);
  }
  let max = 0;
  for (const c of counts.values()) {
    if (c > max) max = c;
  }
  const topOptions = [...counts.entries()].filter(([, c]) => c === max).map(([id]) => id);
  if (topOptions.length === 1) {
    const winner = topOptions[0];
    if (winner === RANDOM_VOTE) {
      if (eligibleGameIds.length === 0) return { kind: "no_votes" };
      const idx = Math.floor(rand() * eligibleGameIds.length);
      return { kind: "random", gameId: eligibleGameIds[idx] };
    }
    return { kind: "chosen", gameId: winner };
  }
  return { kind: "tie", candidates: topOptions };
}
