// AUTO-GENERATED by scripts/build-hooks.ts — do not edit by hand.

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/lib/core/hooks-entry.ts
var hooks_entry_exports = {};
__export(hooks_entry_exports, {
  ACHIEVEMENTS_MODEL_DEFAULT: () => ACHIEVEMENTS_MODEL_DEFAULT,
  RANDOM_VOTE: () => RANDOM_VOTE,
  buildClaudeRequest: () => buildClaudeRequest,
  buildPrompt: () => buildPrompt,
  computeMatchAwards: () => computeMatchAwards,
  emptyStats: () => emptyStats,
  evaluateTrigger: () => evaluateTrigger,
  extractClaudeText: () => extractClaudeText,
  levelFromXp: () => levelFromXp,
  parseAchievements: () => parseAchievements,
  progressToNextLevel: () => progressToNextLevel,
  resolveVotes: () => resolveVotes,
  xpForAction: () => xpForAction
});
module.exports = __toCommonJS(hooks_entry_exports);

// src/lib/core/achievements.ts
var TWO_CHAR_OPS = /* @__PURE__ */ new Set(["&&", "||", ">=", "<=", "==", "!="]);
var ONE_CHAR_OPS = /* @__PURE__ */ new Set(["(", ")", ">", "<"]);
function tokenize(input) {
  const tokens = [];
  let i = 0;
  while (i < input.length) {
    const c = input[i];
    if (c === " " || c === "	" || c === "\n" || c === "\r") {
      i++;
      continue;
    }
    if (/\d/.test(c)) {
      let j = i;
      let sawDot = false;
      while (j < input.length) {
        const cj = input[j];
        if (cj === ".") {
          if (sawDot) throw new Error("multiple dots in number");
          sawDot = true;
          j++;
        } else if (/\d/.test(cj)) {
          j++;
        } else {
          break;
        }
      }
      tokens.push({ type: "NUM", value: input.slice(i, j) });
      i = j;
      continue;
    }
    if (/[a-zA-Z_]/.test(c)) {
      let j = i;
      while (j < input.length && /\w/.test(input[j])) j++;
      tokens.push({ type: "IDENT", value: input.slice(i, j) });
      i = j;
      continue;
    }
    const two = input.slice(i, i + 2);
    if (TWO_CHAR_OPS.has(two)) {
      tokens.push({ type: two, value: two });
      i += 2;
      continue;
    }
    if (ONE_CHAR_OPS.has(c)) {
      tokens.push({ type: c, value: c });
      i++;
      continue;
    }
    throw new Error(`unexpected character: ${c}`);
  }
  return tokens;
}
var Parser = class {
  constructor(tokens, stats) {
    this.tokens = tokens;
    this.stats = stats;
    __publicField(this, "pos", 0);
  }
  peek() {
    return this.tokens[this.pos];
  }
  consume() {
    const t = this.tokens[this.pos++];
    if (!t) throw new Error("unexpected end of expression");
    return t;
  }
  parseExpr() {
    return this.parseOr();
  }
  parseOr() {
    let left = this.parseAnd();
    while (this.peek()?.type === "||") {
      this.consume();
      const right = this.parseAnd();
      left = left || right;
    }
    return left;
  }
  parseAnd() {
    let left = this.parseCmp();
    while (this.peek()?.type === "&&") {
      this.consume();
      const right = this.parseCmp();
      left = left && right;
    }
    return left;
  }
  parseCmp() {
    const left = this.parsePrimary();
    const op = this.peek();
    if (op && [">=", "<=", ">", "<", "==", "!="].includes(op.type)) {
      this.consume();
      const right = this.parsePrimary();
      switch (op.type) {
        case ">=":
          return left >= right;
        case "<=":
          return left <= right;
        case ">":
          return left > right;
        case "<":
          return left < right;
        case "==":
          return left === right;
        case "!=":
          return left !== right;
      }
    }
    return left !== 0;
  }
  parsePrimary() {
    const t = this.consume();
    if (t.type === "NUM") return parseFloat(t.value);
    if (t.type === "IDENT") return this.stats[t.value] ?? 0;
    if (t.type === "(") {
      const val = this.parseExpr();
      const close = this.consume();
      if (close.type !== ")") throw new Error("expected )");
      return val ? 1 : 0;
    }
    throw new Error(`unexpected token: ${t.type}`);
  }
  atEnd() {
    return this.pos >= this.tokens.length;
  }
};
function evaluateTrigger(expr, stats) {
  try {
    const tokens = tokenize(expr);
    if (tokens.length === 0) return false;
    const parser = new Parser(tokens, stats);
    const result = parser.parseExpr();
    if (!parser.atEnd()) return false;
    return result;
  } catch {
    return false;
  }
}

// src/lib/core/xp.ts
var XP_PER_ACTION = {
  participate_match: 10,
  win_match: 15,
  rate_game: 2,
  host_session: 50,
  co_host_session: 30,
  add_game: 25,
  achievement_common: 10,
  achievement_rare: 25,
  achievement_epic: 50
};
function xpForAction(action) {
  return XP_PER_ACTION[action];
}
function xpForLevel(level) {
  if (!Number.isInteger(level) || level < 1) {
    throw new Error(`level must be an integer >= 1, got ${level}`);
  }
  let total = 0;
  for (let k = 1; k < level; k++) {
    total += Math.floor(100 * Math.pow(k, 1.5));
  }
  return total;
}
function levelFromXp(xp) {
  if (xp <= 0) return 1;
  let lvl = 1;
  while (xpForLevel(lvl + 1) <= xp) {
    lvl++;
  }
  return lvl;
}
function progressToNextLevel(xp) {
  const level = levelFromXp(xp);
  const base = xpForLevel(level);
  const next = xpForLevel(level + 1);
  const into = xp - base;
  const needed = next - base;
  return { level, into, needed, ratio: into / needed };
}

// src/lib/core/awards.ts
function emptyStats(userId) {
  return {
    userId,
    totalWins: 0,
    winsOnGame: 0,
    lossesOnGame: 0,
    currentStreakWins: 0,
    currentStreakLosses: 0
  };
}
var RARITY_TO_ACTION = {
  common: "achievement_common",
  rare: "achievement_rare",
  epic: "achievement_epic"
};
function computeMatchAwards(outcome, statsByUser, achievementsForGame, alreadyUnlocked) {
  const results = [];
  for (const player of outcome.players) {
    const lines = [];
    lines.push({
      action: "participate_match",
      xp: xpForAction("participate_match")
    });
    if (player.won) {
      lines.push({ action: "win_match", xp: xpForAction("win_match") });
    }
    if (player.liked === true || player.liked === false) {
      lines.push({ action: "rate_game", xp: xpForAction("rate_game") });
    }
    const prev = statsByUser[player.userId] ?? emptyStats(player.userId);
    const postStats = advanceStats(prev, player.won, outcome.durationSeconds);
    const existing = alreadyUnlocked[player.userId] ?? /* @__PURE__ */ new Set();
    const unlocked = [];
    for (const ach of achievementsForGame) {
      if (existing.has(ach.id)) continue;
      if (evaluateTrigger(ach.triggerExpr, postStats)) {
        unlocked.push(ach.id);
        const action = RARITY_TO_ACTION[ach.rarity];
        lines.push({ action, xp: xpForAction(action) });
      }
    }
    const xpDelta = lines.reduce((sum, line) => sum + line.xp, 0);
    results.push({
      userId: player.userId,
      xpDelta,
      xpBreakdown: lines,
      unlockedAchievementIds: unlocked
    });
  }
  return results;
}
function advanceStats(prev, won, durationSeconds) {
  return {
    total_wins: prev.totalWins + (won ? 1 : 0),
    wins_on_game: prev.winsOnGame + (won ? 1 : 0),
    losses_on_game: prev.lossesOnGame + (won ? 0 : 1),
    current_streak_wins: won ? prev.currentStreakWins + 1 : 0,
    current_streak_losses: won ? 0 : prev.currentStreakLosses + 1,
    match_duration_seconds: durationSeconds,
    match_duration_minutes: durationSeconds / 60
  };
}

// src/lib/core/achievement-generator.ts
var ACHIEVEMENTS_MODEL_DEFAULT = "claude-haiku-4-5";
var MAX_TOKENS = 2048;
var MAX_ACHIEVEMENTS = 10;
var SYSTEM_PROMPT = `You generate personalized board-game achievements.

Output strict JSON: an array of 6 objects, each with:
  - "title": string, 1-80 chars, punchy and game-flavored
  - "description": string, 1-300 chars, include a pun or in-joke about the game
  - "triggerExpr": a safe expression using only these variables:
      total_wins, wins_on_game, losses_on_game,
      current_streak_wins, current_streak_losses,
      match_duration_seconds, match_duration_minutes
    and these operators: >=, <=, >, <, ==, !=, &&, ||, ( )
    No function calls, no property access, no string literals.
  - "rarity": one of "common", "rare", "epic"

Cover these buckets across the 6 outputs:
  1. First win (common)
  2. Five wins on this game (common)
  3. Twenty-five wins (rare)
  4. First loss, with a consoling pun (common)
  5. A win streak (>= 3) (rare)
  6. An edge case specific to the game (epic) \u2014 e.g. a very long match
     (match_duration_minutes >= <reasonable-for-this-game>) or a
     loyal-loser combo (losses_on_game >= 10 && wins_on_game == 0).

Return ONLY the JSON array. No prose, no markdown.`;
function buildPrompt(game) {
  const cats = game.categories?.length ? `Categories: ${game.categories.join(", ")}.` : "Categories: unspecified.";
  const desc = game.description?.trim() ? `Description: ${game.description.trim()}` : "";
  const user = [
    `Game: ${game.name}`,
    `Players: ${game.minPlayers}-${game.maxPlayers}`,
    cats,
    desc
  ].filter(Boolean).join("\n");
  return { system: SYSTEM_PROMPT, user };
}
function buildClaudeRequest(prompt, opts = {}) {
  const body = {
    model: opts.model ?? ACHIEVEMENTS_MODEL_DEFAULT,
    max_tokens: opts.maxTokens ?? MAX_TOKENS,
    system: [
      {
        type: "text",
        text: prompt.system,
        cache_control: { type: "ephemeral" }
      }
    ],
    messages: [{ role: "user", content: prompt.user }]
  };
  return JSON.stringify(body);
}
function extractClaudeText(response) {
  if (!response || typeof response !== "object") return "";
  const content = response.content;
  if (!Array.isArray(content)) return "";
  for (const block of content) {
    if (block && typeof block === "object" && block.type === "text" && typeof block.text === "string") {
      return block.text;
    }
  }
  return "";
}
var RARITIES = /* @__PURE__ */ new Set(["common", "rare", "epic"]);
var LIMITS = {
  title: { min: 1, max: 80 },
  description: { min: 1, max: 300 },
  triggerExpr: { min: 1, max: 500 }
};
function parseAchievements(raw) {
  const json = stripFence(raw);
  let parsed;
  try {
    parsed = JSON.parse(json);
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const item of parsed) {
    if (out.length >= MAX_ACHIEVEMENTS) break;
    const normalized = normalizeAchievement(item);
    if (!normalized) continue;
    if (seen.has(normalized.triggerExpr)) continue;
    seen.add(normalized.triggerExpr);
    out.push(normalized);
  }
  return out;
}
function stripFence(raw) {
  const trimmed = raw.trim();
  const match = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (match && match[1]) return match[1].trim();
  return trimmed;
}
function normalizeAchievement(item) {
  if (!item || typeof item !== "object") return null;
  const obj = item;
  const title = asString(obj.title, LIMITS.title.min, LIMITS.title.max);
  const description = asString(
    obj.description,
    LIMITS.description.min,
    LIMITS.description.max
  );
  const triggerExpr = asString(
    obj.triggerExpr,
    LIMITS.triggerExpr.min,
    LIMITS.triggerExpr.max
  );
  const rarity = typeof obj.rarity === "string" ? obj.rarity : "";
  if (!title || !description || !triggerExpr || !RARITIES.has(rarity)) {
    return null;
  }
  if (!exprParses(triggerExpr)) return null;
  return {
    title,
    description,
    triggerExpr,
    rarity
  };
}
function asString(v, min, max) {
  if (typeof v !== "string") return null;
  const s = v.trim();
  if (s.length < min || s.length > max) return null;
  return s;
}
function exprParses(expr) {
  const huge = {
    total_wins: 1e9,
    wins_on_game: 1e9,
    losses_on_game: 1e9,
    current_streak_wins: 1e9,
    current_streak_losses: 1e9,
    match_duration_seconds: 1e9,
    match_duration_minutes: 1e9
  };
  const zero = Object.fromEntries(
    Object.keys(huge).map((k) => [k, 0])
  );
  const a = evaluateTrigger(expr, huge);
  const b = evaluateTrigger(expr, zero);
  return a || b;
}

// src/lib/core/voting.ts
var RANDOM_VOTE = "__random__";
function resolveVotes(votes, eligibleGameIds, rand = Math.random) {
  if (votes.length === 0) return { kind: "no_votes" };
  const counts = /* @__PURE__ */ new Map();
  for (const v of votes) {
    counts.set(v.gameId, (counts.get(v.gameId) ?? 0) + 1);
  }
  let max = 0;
  for (const c of counts.values()) {
    if (c > max) max = c;
  }
  const topOptions = [...counts.entries()].filter(([, c]) => c === max).map(([id]) => id);
  if (topOptions.length === 1) {
    const winner = topOptions[0];
    if (winner === RANDOM_VOTE) {
      if (eligibleGameIds.length === 0) return { kind: "no_votes" };
      const idx = Math.floor(rand() * eligibleGameIds.length);
      return { kind: "random", gameId: eligibleGameIds[idx] };
    }
    return { kind: "chosen", gameId: winner };
  }
  return { kind: "tie", candidates: topOptions };
}
